In [29]:
import pandas as pd
import numpy as np

In [30]:
teams = pd.read_csv("teams.csv")

In [32]:
teams.head(10)

  team  year  athletes  events   age  height  weight  prev_medals  medals
0  AFG  1964         8       8  22.0   161.0    64.2          0.0       0
1  AFG  1968         5       5  23.2   170.2    70.0          0.0       0
2  AFG  1972         8       8  29.0   168.3    63.8          0.0       0
3  AFG  1980        11      11  23.6   168.4    63.2          0.0       0
4  AFG  2004         5       5  18.6   170.8    64.8          0.0       0
5  AFG  2008         4       4  22.5   179.2    62.8          0.0       1
6  AFG  2012         6       6  24.8   171.7    60.8          1.0       1
7  AFG  2016         3       3  24.7   173.7    74.0          1.0       0
8  AHO  1964         4       4  28.5   171.2    69.4          0.0       0
9  AHO  1968         5       4  31.0   173.2    67.8          0.0       0

In [33]:
X = teams[["athletes", "prev_medals"]].copy()
y = teams[["medals"]].copy()

In [39]:
X # this is the columns that will be used for training

      athletes  prev_medals  intercept
0            8          0.0          1
1            5          0.0          1
2            8          0.0          1
3           11          0.0          1
4            5          0.0          1
...        ...          ...        ...
2009        26          0.0          1
2010        14          0.0          1
2011        16          3.0          1
2012         9          4.0          1
2013        31          0.0          1

[2014 rows x 3 columns]

In [37]:
y # this is the column that will be used for prediction

      medals
0          0
1          0
2          0
3          0
4          0
...      ...
2009       0
2010       3
2011       4
2012       0
2013       0

[2014 rows x 1 columns]

In [38]:
X["intercept"] = 1

In [42]:
X = X[["intercept", "athletes", "prev_medals"]] # adds new column intercept to x data frame

In [43]:
X

      intercept  athletes  prev_medals
0             1         8          0.0
1             1         5          0.0
2             1         8          0.0
3             1        11          0.0
4             1         5          0.0
...         ...       ...          ...
2009          1        26          0.0
2010          1        14          0.0
2011          1        16          3.0
2012          1         9          4.0
2013          1        31          0.0

[2014 rows x 3 columns]

In [46]:
X_T = X.T # x is tranposed

In [47]:
X_T

,0,1,2,3,4,5,6,7,8,9,...,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013
intercept,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
athletes,8.0,5.0,8.0,11.0,5.0,4.0,6.0,3.0,4.0,5.0,...,52.0,20.0,47.0,28.0,21.0,26.0,14.0,16.0,9.0,31.0
prev_medals,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,...,0.0,15.0,0.0,0.0,0.0,0.0,0.0,3.0,4.0,0.0

In [12]:
B = np.linalg.inv(X_T @ X) @ X_T @ y

In [13]:
B

     medals
0 -1.961889
1  0.071112
2  0.734137

In [14]:
B.index = X.columns

In [15]:
B

               medals
intercept   -1.961889
athletes     0.071112
prev_medals  0.734137

In [16]:
predictions = X @ B

In [17]:
predictions

        medals
0    -1.392992
1    -1.606329
2    -1.392992
3    -1.179656
4    -1.606329
...        ...
2009 -0.112974
2010 -0.966319
2011  1.378315
2012  1.614667
2013  0.242587

[2014 rows x 1 columns]

In [18]:
SSR = ((y - predictions) ** 2).sum()

In [19]:
SSR

medals    290620.124598
dtype: float64

In [20]:
TSS = ((y - y.mean()) ** 2).sum()

In [21]:
TSS

medals    2.276322e+06
dtype: float64

In [22]:
R2 = 1 - (SSR / TSS)

In [23]:
R2

medals    0.872329
dtype: float64

In [24]:
from sklearn.linear_model import LinearRegression

In [25]:
lr = LinearRegression()

In [26]:
lr.fit(teams[["athletes", "prev_medals"]], teams[["medals"]])

LinearRegression()

In [27]:
lr.intercept_

array([-1.96188939])

In [28]:
lr.coef_

array([[0.07111214, 0.73413679]])